version: '3.8'

services:

  # [p] reverse proxy
  nginx:
    image: nginx:1.20.1
    container_name: container-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - frontend-react # wait for the frontend container to be started
      - backend-golang # wait for the backend container to be started

  # [f] frontend services
  frontend-react:
    image: image-frontend-react
    container_name: container-frontend-react # This will name the container hello-front-dev
    build:
      context: ./f # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    environment:
      - BACKEND_HOSTNAME=http://localhost/api/
    volumes:
      - ./f/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    depends_on:
      - "backend-golang"


  # [b] backend services
  backend-golang:
    container_name: container-backend-golang 
    build: 
      context: ./b
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./b/:/usr/src/app
    ports:
      - "8000"
          