services:
  ### NGINX REVERSE PROXY ###

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: container-todo-app-reverse-proxy
    depends_on:
      - todo-frontend # wait for the frontend container to be started

  ### FRONT ###

  todo-frontend:
    image: todo-frontend
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
    container_name: container-todo-frontend # This will name the container hello-front-dev
    depends_on:
      - todo-backend

  ### BACK ###

  todo-backend:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    ports:
      - 8000:3000
    environment:
      - MONGO_URL=mongodb://root:password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379/
    container_name: container-todo-backend
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: container-todo-backend-mongo

  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    container_name: container-todo-backend-redis

volumes:
  mongo_data:
  todo-backend:
  todo-frontend:
  nginx.conf:
